kind: Pod
apiVersion: v1
metadata:
  name: testpod3
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hey_Uzair; sleep 5 ; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Devops_Engineer; sleep 5 ; done"]

      env:                        # List of environment variables to be used inside the pod
      - name: MYNAME
        value: Uzair