kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: nginx
      ports:
       - containerPort: 80

__________________________


kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80